# This file was auto-generated by Fern from our API Definition. It is now manually updated.

import enum


class ScorecardEnvironment(enum.Enum):
    DEFAULT = "https://api.getscorecard.ai"
    TELEMETRY_KEY = ""
    TELEMETRY_URL = "https://telemetry.getscorecard.ai"